config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  authenticated :user do
    root 'student/dashboard#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated
    get 'about', to: 'home#about'
    get 'pricing', to: 'home#pricing'
    get 'clients', to: 'home#clients'
  end

  namespace :student, path: '/s' do

    resources :profile

    resources :dashboard

    resources :assignments

    resources :attendance, as: 'attends'
  end

  namespace :admin, path: '/a' do

    resources :dashboard
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin, :teacher, :student]
  after_initialize :set_default_role, :if => :new_record?

  has_one_attached :avatar
  has_one_attached :signature

  has_one :student_profile, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :student_profile

  validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
              file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
  validates :signature, file_size: { less_than_or_equal_to: 5.megabytes },
              file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }

  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery with: :exception

	private

	def after_sign_in_path_for(resource)
    student_dashboard_index_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end

  def about
  end

  def pricing
  end

  def clients
  end
end

app/controllers/student/assignments_controller.rb
class Student::AssignmentsController < StudentController
  before_action :set_current_user

  def index
  end

  private

  def set_current_user
    @user = current_user
  end
end

app/controllers/student/attendance_controller.rb
class Student::AttendanceController < StudentController

  def index
	end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < StudentController

  def index
  end
end

app/controllers/student/profile_controller.rb
class Student::ProfileController < StudentController

  def index
  	@current_user = current_user
    @blood_group = blood_groups.select { |b| b.second == "#{@current_user.blood_group}" }.first.first
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  include StudentHelper
  layout 'student'
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'student', only: %i[edit]
  before_action :configure_permitted_parameters

  def edit
    @current_user = current_user
    @current_user.build_student_profile if @current_user.student_profile.nil?
  end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :first_name, :last_name)}
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:signature, :avatar, :email, :password,
                                                                        :password_confirmation, :current_password,
                                                                        :first_name, :last_name, :gender, :b_day, :b_month, :b_year,
                                                                        :phone, :address, :blood_group, :aadhaar_number,
                                                                        :headline,
                                                                        student_profile_attributes: [:id, :website, :linkedin,
                                                                          :github, :surname, :roll_number,
                                                                          :father_name, :mother_name,
                                                                          :parent_phone, :a_day, :a_month, :a_year, :admisssion_quota,
                                                                          :campus_type, :religion, :caste, :category, :nationality,
                                                                          :state, :district, :taluk])}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def greeting_time
    current_time = Time.now.to_i
    midnight = Time.now.beginning_of_day.to_i
    noon = Time.now.middle_of_day.to_i
    five_pm = Time.now.change(:hour => 17 ).to_i

    case
     when midnight.upto(noon).include?(current_time)
      "Good Morning"
     when noon.upto(five_pm).include?(current_time)
       "Good Afternoon"
     when five_pm.upto(midnight + 1.day).include?(current_time)
      "Good Evening"
    end
  end

  def active_nav_link url
    if current_page?(url)
      'fw-medium active nav-link-underline'
    end
  end
end

app/helpers/student_helper.rb
module StudentHelper

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true, timeOut: 2500 })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end

  def gender
    [['Male', 'M'], ['Female', 'F'], ['Other', 'O']]
  end

  def blood_groups
    [['A+', 'a_pos'], ['A-', 'a_neg'], ['B+', 'b_pos'], ['B-', 'b_neg'], ['O+', 'o_pos'],
    ['O-', 'o_neg'], ['AB+', 'ab_pos'], ['AB-', 'ab_neg']]
  end

  def active_url url
    if current_page?(url)
      'side-nav-active-link'
    end
  end
end

app/views/home/clients.html.haml
%main#top.main
  %section#clients.section-bg
    %br
    %br
    %br
    %br
    .container
      .section-header
        %h3 Our CLients
        %p Meet our happy clients
      .row.no-gutters.clients-wrap.clearfix.wow.fadeInUp{:style => "visibility: visible; animation-name: fadeInUp;"}
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460149/abof.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460224/cropped-cropped-20170720-lucuLogo-squ2-e1500543540803.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460269/104840a62d46c05d285762857fecb61a.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460358/client-4.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460379/client-5.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460398/client-6.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://res.cloudinary.com/dxfq3iotg/image/upload/v1559460418/client-7.png"}/
        .col-lg-3.col-md-4.col-xs-6
          .client-logo
            %img.img-fluid{:alt => "", :src => "https://bootstrapmade.com/demo/themes/NewBiz/img/clients/client-8.png"}/

app/views/layouts/_admin_footer.html.haml
%footer.main-footer
  %strong
    Copyright © 2014-2019
    = succeed "." do
      %a{:href => "http://adminlte.io"} AdminLTE.io
  All rights reserved.
  .float-right.d-none.d-sm-inline-block
    %b Version
    3.0.5

app/views/layouts/_student_footer.html.haml
%footer.main-footer
  %strong
    Copyright © 2014-2019
    = succeed "." do
      %a{:href => "http://adminlte.io"} AdminLTE.io
  All rights reserved.
  .float-right.d-none.d-sm-inline-block
    %b Version
    3.0.5

app/views/layouts/_student_side_nav.html.haml
%aside.main-sidebar.sidebar-dark-purple-1.elevation-4
  / Brand Logo
  %a.brand-link{:href => "/s/dashboard"}
    = image_tag 'ams_app_icon.png', alt: 'icon', class: 'brand-image img-circle elevation-3', style: "opacity: .8"
    %span.brand-text.font-weight-light AmsApp
  / Sidebar
  .sidebar
    / Sidebar user panel (optional)
    .user-panel.mt-3.pb-3.mb-3.d-flex
      .image
        - if current_user.avatar.present?
          = image_tag(current_user.avatar.variant(resize_to_fill: [150, 150]), class: "img-circle elevation-2")
        - else
          = image_tag "default_profile.png", alt: 'image', class: 'img-circle elevation-2', width: "150px"
      .info
        = link_to current_user.full_name.titleize, student_profile_index_path, class: 'd-block'
    / Sidebar Menu
    %nav.mt-2
      %ul.nav.nav-pills.nav-sidebar.flex-column{"data-accordion" => "false", "data-widget" => "treeview", :role => "menu"}
        /
          Add icons to the links using the .nav-icon class
          with font-awesome or any other icon font library
        / %li.nav-item.has-treeview.menu-open
        /   %a.nav-link.active{:href => "#"}
        /     %i.nav-icon.fas.fa-tachometer-alt
        /     %p
        /       Dashboard
        /       %i.right.fas.fa-angle-left
        /   %ul.nav.nav-treeview
        /     %li.nav-item
        /       %a.nav-link.active{:href => "./index.html"}
        /         %i.far.fa-circle.nav-icon
        /         %p Dashboard v1
        /     %li.nav-item
        /       %a.nav-link{:href => "./index2.html"}
        /         %i.far.fa-circle.nav-icon
        /         %p Dashboard v2
        /     %li.nav-item
        /       %a.nav-link{:href => "./index3.html"}
        /         %i.far.fa-circle.nav-icon
        /         %p Dashboard v3
        %li.nav-item{class: active_url(student_assignments_path)}
          = link_to student_assignments_path, class: 'nav-link' do
            %i.nav-icon.fa-solid.fa-list
            %p
              Assignments
        %li.nav-item{class: active_url(student_attends_path)}
          = link_to student_attends_path, class: 'nav-link' do
            %i.nav-icon.fa-solid.fa-calendar-check
            %p
              Attendance
              / %span.right.badge.badge-danger New
  /       %li.nav-item.has-treeview
  /         %a.nav-link{:href => "#"}
  /           %i.nav-icon.fas.fa-copy
  /           %p
  /             Layout Options
  /             %i.fas.fa-angle-left.right
  /             %span.badge.badge-info.right 6
  /         %ul.nav.nav-treeview
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/top-nav.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Top Navigation
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/top-nav-sidebar.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Top Navigation + Sidebar
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/boxed.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Boxed
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/fixed-sidebar.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Fixed Sidebar
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/fixed-topnav.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Fixed Navbar
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/fixed-footer.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Fixed Footer
  /           %li.nav-item
  /             %a.nav-link{:href => "pages/layout/collapsed-sidebar.html"}
  /               %i.far.fa-circle.nav-icon
  /               %p Collapsed Sidebar
  /   /.sidebar-menu
  / /.sidebar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AmsApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('ams_app_icon.png')
    %link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css", :integrity => "sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==", :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800&display=swap", :rel => "stylesheet"}/
  %body
    = render '/shared/home_navbar'
    = yield
    = render '/shared/home_footer'
    = render '/shared/scroll_to_top_button'

app/views/layouts/student.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AmsApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'student', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'student', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('ams_app_icon.png')
    %link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css", :integrity => "sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==", :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
  %body.hold-transition.sidebar-mini.layout-fixed
    .wrapper
      = render "layouts/student_nav"
      = render "layouts/student_side_nav"
      .content-wrapper
        = toastr_flash
        = yield
      / = render "layouts/student_footer"

app/views/shared/_alerts.html.haml
.alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
  = alert
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/shared/_app_logo.html.haml
.d-flex.align-items-center
  = image_tag 'ams_app_icon.png', alt: 'icon', class: 'brand-image img-circle elevation-3 mt-2 ms-2', height: '50', width: '50'
  %h2.fw-normal.mt-3.ms-2 AmsApp

app/views/student/profile.html.haml
%section{:style => "background-color: #eee;"}
  .container.py-3
    .d-flex.justify-content-between
      %h2.mb-3 My Profile
      = link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary mb-3'
    .row
      .col
        %nav.bg-light.rounded-3.p-3.mb-4{"aria-label" => "breadcrumb"}
          %ol.breadcrumb.mb-0
            %li.breadcrumb-item
              = link_to 'Dashboard', s_dashboard_path, class: 'text-black'
            %li.breadcrumb-item.active{"aria-current" => "page"} Profile
    .row
      .col-lg-4
        .card.mb-4
          .card-body.text-center
            - if @current_user.avatar.present?
              = image_tag(@current_user.avatar.variant(resize_to_fill: [150, 150]), class: "rounded-circle img-fluid")
            - else
              = image_tag "default_profile.png", alt: 'image', class: 'rounded-circle img-fluid', width: "150px"
            %h5.my-3= @current_user.name.titleize
            %p.text-muted.mb-1= @current_user.headline.titleize
            %p.text-muted.mb-4= @current_user.address
            / .d-flex.justify-content-center.mb-2
            /   %button.btn.btn-primary{:type => "button"} Follow
            /   %button.btn.btn-outline-primary.ms-1{:type => "button"} Message
        .card.mb-4
          .card-body.p-0
            %ul.list-group.list-group-flush.rounded-3
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Course
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.course
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Stream
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.stream
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 University Reg No.
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.university_reg_number
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Admission No.
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.admisssion_number
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Admission Date
                .col-sm-5
                  %p.text-muted.mb-0= "#{@current_user.student_profile.a_day} - #{@current_user.student_profile.a_month} - #{@current_user.student_profile.a_year}"
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Admission Quota
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.admisssion_quota
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Current Semester
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.current_semester
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                .col-sm-5
                  %p.mb-0 Roll Number
                .col-sm-5
                  %p.text-muted.mb-0= @current_user.student_profile.roll_number
        .card.mb-4
          .card-body.p-0
            %ul.list-group.list-group-flush.rounded-3
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                %i.fas.fa-globe.fa-lg.text-warning
                %a.mb-0.text-dark{href: "#{@current_user.student_profile.website}", target: "_blank"}= @current_user.student_profile.website
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                %i.fab.fa-linkedin.fa-lg{style: "color: #0077b5;"}
                %a.mb-0.text-dark{href: "#{@current_user.student_profile.linkedin}", target: "_blank"}= @current_user.student_profile.linkedin
              %li.list-group-item.d-flex.justify-content-between.align-items-center.p-3
                %i.fab.fa-github.fa-lg{style: "color: #333333;"}
                %a.mb-0.text-dark{href: "#{@current_user.student_profile.github}", target: "_blank"}= @current_user.student_profile.github
        .card.mb-4
          .card-body.text-center
            %h5.mb-3 Signature
            - if @current_user.signature.present?
              = image_tag(@current_user.signature.variant(resize_to_fill: [150, 150]))
              .d-flex.justify-content-center.mb-2.mt-3
                = link_to 'Preview', rails_blob_path(@current_user.signature, disposition: 'preview'), class: 'btn btn-secondary me-3', target: '_blank'
                = link_to 'Download', rails_blob_path(@current_user.signature, disposition: 'attachment'), class: 'btn btn-outline-secondary'
            - else
              %p Empty
      .col-lg-8
        .card.mb-4
          .card-body
            .row
              .col-sm-3
                %p.mb-0 Full Name
              .col-sm-9
                %p.text-muted.mb-0= @current_user.name.titleize
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Surname
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.surname.titleize
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Email
              .col-sm-9
                %p.text-muted.mb-0= @current_user.email
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Phone
              .col-sm-9
                %p.text-muted.mb-0= @current_user.phone
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Address
              .col-sm-9
                %p.text-muted.mb-0= @current_user.address
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Aadhaar Number
              .col-sm-9
                %p.text-muted.mb-0= @current_user.aadhaar_number
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Gender
              .col-sm-9
                %p.text-muted.mb-0= @current_user.gender
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Blood Group
              .col-sm-9
                %p.text-muted.mb-0= @blood_group
            %hr/
            .row
              .col-sm-3
                %p.mb-0 D.O.B
              .col-sm-9
                %p.text-muted.mb-0= "#{@current_user.b_day} - #{@current_user.b_month} - #{@current_user.b_year}"
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Father's Name
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.father_name
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Mother's Name
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.mother_name
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Parent Phone
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.parent_phone
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Campus Type
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.campus_type
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Religion
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.religion
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Caste
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.caste
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Category
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.category
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Nationality
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.nationality
            %hr/
            .row
              .col-sm-3
                %p.mb-0 state
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.state
            %hr/
            .row
              .col-sm-3
                %p.mb-0 District
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.district
            %hr/
            .row
              .col-sm-3
                %p.mb-0 Taluk
              .col-sm-9
                %p.text-muted.mb-0= @current_user.student_profile.taluk
        / .row
        /   .col-md-6
        /     .card.mb-4.mb-md-0
        /       .card-body
        /         %p.mb-4
        /           %span.text-primary.font-italic.me-1 assigment
        /           Project Status
        /         %p.mb-1{:style => "font-size: .77rem;"} Web Design
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Website Markup
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "72", :role => "progressbar", :style => "width: 72%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} One Page
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "89", :role => "progressbar", :style => "width: 89%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Mobile Template
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "55", :role => "progressbar", :style => "width: 55%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Backend API
        /         .progress.rounded.mb-2{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "66", :role => "progressbar", :style => "width: 66%"}
        /   .col-md-6
        /     .card.mb-4.mb-md-0
        /       .card-body
        /         %p.mb-4
        /           %span.text-primary.font-italic.me-1 assigment
        /           Project Status
        /         %p.mb-1{:style => "font-size: .77rem;"} Web Design
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "80", :role => "progressbar", :style => "width: 80%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Website Markup
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "72", :role => "progressbar", :style => "width: 72%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} One Page
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "89", :role => "progressbar", :style => "width: 89%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Mobile Template
        /         .progress.rounded{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "55", :role => "progressbar", :style => "width: 55%"}
        /         %p.mt-4.mb-1{:style => "font-size: .77rem;"} Backend API
        /         .progress.rounded.mb-2{:style => "height: 5px;"}
        /           .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "66", :role => "progressbar", :style => "width: 66%"}